name: "DualCore: Test Build"
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - DualCore/**
      - .github/workflows/DualCore-CI.yml
  push:
    branches: [main]
    paths:
      - DualCore/**
      - .github/workflows/DualCore-CI.yml
  schedule:
    - cron: '00 20 * * 6'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: ".ci/vcpkg-configuration.json"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Build HelloWorld with AC6 and all contexts
        working-directory: ./DualCore/
        run: cbuild HelloWorld.csolution.yml --packs --toolchain AC6

      - name: Upload HelloWorld AC6 build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: HelloWorld_AC6
          path: |
            ./DualCore/out/
          retention-days: 1